name: Generate Snake

on:
  schedule: # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generates the snake animation from a user's contributions graph
      - uses: Platane/snk@v3
        with:
          github_user_name: deeshath  
          outputs: dist/snake.svg

      # Pushes the generated snake.svg to the repository
      - name: Push Snake SVG to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # The output branch where the snake will be stored
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
