name: Generate Snake

on:
  schedule: # Runs at 12am UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generates a snake game from a github user contributions graph
      - uses: Platane/snk@v2
        with:
          github_user_name: deeshath
          outputs: dist/snake.svg

      # Push the content to the output branch
      # The output branch name is "output". It can be any branch that you prefer
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
